apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-
spec:
  serviceAccountName: build-bot
  params:
    - name: image-repo
      value: quay.io/tillus/chuying-till-application
  pipelineRef:
    name: git-clone
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
